citizen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('citizen_app.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

citizen_app/urls.py
from django.urls import path
from .import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'citizen_app'

urlpatterns = [
    path('', views.news, name='news'),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('pdf/', views.GeneratePdf.as_view(), name='pdf'),
    path('showreadmore/<title>', csrf_exempt(views.showReadMore), name='showreadmore'),
    path('report/', views.report, name='report'),
    path('payment/', views.payment, name='payment'),
]

citizen_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
		help_texts = {
		'username' : None,
	}

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

citizen_app/views.py
import os
import datetime
from django.shortcuts import render, redirect
import requests
from django.http import JsonResponse
import json
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods

from newsapi import NewsApiClient
from requests.api import request

from django.urls import reverse
from django.views.generic import FormView
from django.views.generic import View
from django.views.generic import TemplateView
from paypal.standard.forms import PayPalPaymentsForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from .forms import NewUserForm

from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from .utils import render_to_pdf
from django.template.loader import get_template

from django.contrib import messages
from datetime import date

import reportlab                  # generates reports

# news API from newsapi.org
API_KEY = '8d8d51e07d8d40078290e6f9a8c68ed4'

class DataManager:
    data = []

    def setData(self, d):
        self.data = d

    def getData(self):
        return self.data


# obtaining data from the news API
def news(request):
    date = datetime.datetime(2021, 9, 19)
    oldest = request.GET.get('date')
    category = request.GET.get('category')
    popularity = request.GET.get('popularity')

    if request.method == 'POST':
        qInTitle = request.POST['search']

        url = f'https://newsapi.org/v2/everything?q={qInTitle}&from={oldest}&sortBy={popularity}&apiKey={API_KEY}'
        response = requests.get(url)
        data = response.json()

        articles = data['articles']

    elif category:
        url = f'https://newsapi.org/v2/top-headlines?category={category}&sortBy=relevancy&language=en&apiKey={API_KEY}'
        response = requests.get(url)
        data = response.json()

        articles = data['articles']

    else:
        url = f'https://newsapi.org/v2/top-headlines?country=us&sortBy={popularity}&apiKey={API_KEY}'
        response = requests.get(url)
        data = response.json()

        articles = data['articles']
        uuid = 0
        newData = []
        for article in articles:
            article = {**article, 'uuid': uuid}
            uuid = uuid + 1
            article['source']['id'] = uuid

        data_manager = DataManager()
        data_manager.setData(articles)

    context = {'articles': articles}
    return render(request, 'home.html', context)


def report(request):
    return render(request, 'report.html')


# signup page
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("citizen_app:news")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()

    return render(request=request, template_name='accounts/register.html', context={"register_form": form})


# login page
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("citizen_app:news")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="accounts/login.html", context={"login_form": form})

# logout page


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("citizen_app:news")


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@citizendigital.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    messages.success(
                        request, 'A message with reset password instructions has been sent to your inbox.')
                    return redirect("citizen_app:news")
                messages.error(request, 'An invalid email has been entered.')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password_reset.html", context={"password_reset_form": password_reset_form})

# paypal


class PaypalFormView(FormView):
    template_name = 'paypal_form.html'
    form_class = PayPalPaymentsForm

    def get_initial(self):
        return {
            "business": 'sb-h3r9j8948196@business.example.com',
            "amount": 1.00,
            "currency_code": "USD",
            "item_name": 'Article',
            "invoice": 1234,
            "notify_url": self.request.build_absolute_uri(reverse('paypal-ipn')),
            "return_url": self.request.build_absolute_uri(reverse('paypal-return')),
            "cancel_return": self.request.build_absolute_uri(reverse('paypal-cancel')),
            "lc": 'EN',
            "no_shipping": '1',
        }


class PaypalReturnView(TemplateView):
    template_name = 'paypal_success.html'


class PaypalCancelView(TemplateView):
    template_name = 'paypal_cancel.html'


# report view
class GeneratePdf(View):
    def render_data(request):
        url = f'https://newsapi.org/v2/top-headlines?country=us&apiKey={API_KEY}'
        response = requests.get(url)
        data = response.json()

        articles = data['articles']
        uuid = 0
        newData = []
        for article in articles:
            article = {**article, 'uuid': uuid}
            uuid = uuid + 1
            article['source']['id'] = uuid

        data_manager = DataManager()
        data_manager.setData(articles)

        context = {'articles': articles}

    def get(self, request, *args, **kwargs):
        template = get_template('report.html')
        context = {
            "user": request.user,
        }
        html = template.render(context)
        pdf = render_to_pdf('report.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Report_%s.pdf" % ("12341231")
            content = "inline; filename='%s'" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


def showReadMore(request, title):
    if request.method == 'GET':
        url = f'https://newsapi.org/v2/everything?q={title}&apiKey={API_KEY}'
        response = requests.get(url)
        data = response.json()
        context = {'data': data['articles'][0]}
        return render(request, 'readmore.html', context)


def report(request):
    today = date.today()
    url = f'https://newsapi.org/v2/top-headlines?country=us&sortBy=relevancy&apiKey={API_KEY}'
    response = requests.get(url)
    data = response.json()

    articles = data['articles']
    uuid = 0
    newData = []
    for article in articles:
        article = {**article, 'uuid': uuid}
        uuid = uuid + 1
        article['source']['id'] = uuid

    data_manager = DataManager()
    data_manager.setData(articles)

    context = {'articles': articles, "user": request.user, "today": today}
    # return redirect("citizen_app:payment")
    return render(request, 'report.html', context)


def payment(request):
    context = {
        "user": request.user
    }
    return render(request, 'payment.html', context)

citizen_app/templates/home.html
{% extends 'nav.html' %}
  {% block content %}
    {% load static %}
    <!--cards in a row-->
    <div class="top" style="margin-top: 120px; background: whitesmoke;">
      <div class="container">
        <div class="row row-cols-1 row-cols-md-3">
          {% for i in articles %}
          <div class="col mb-4">
            <div class="card h-100">
              <img src="{{i.urlToImage}}" class="card-img-top" alt="...">
              <div class="card-body">
                <p><small>{{i.title}}</h5></small></p>
                <!--paypal-->
                
                {% if user.is_authenticated %}

                  <a class="readmore" target="_blank" href={{i.url}} rel="noopener">Read more...</a>
                    {% else %}
                  <a class="readmore" target="_blank" href="/login" rel="noopener">login to read more </a>  
                {% endif %}
                <hr>
                <br>
                <small>date: {{i.publishedAt}}</small>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
        <p>{{i.content}}</p>
        
      </div>
    <!--end of cards-->
    </div>
    
{% endblock %}
  

citizen_app/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-sm alert-{{ message.tags}}" {% endif %}>
            {{ message }}
        </div>
    {% endfor %}
    </div>
{% endif %}

citizen_app/templates/nav.html
<!DOCTYPE html>
<html>
    <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
    <link rel=”stylesheet” href="css/bootstrap.css">
    <link rel=”stylesheet” href="css/bootstrap-responsive.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/nav.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/home.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Breaking news, Business, Sports, Lifestyle</title>
    </head>
    <body style="background: whitesmoke;">
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm  fixed-top" style="background: black; height: 100px;">
            <div class="container"> 
                <a class="navbar-brand d-flex align-items-center" href="">
                    <a class="nav-item px-lg-2" href="{% url 'citizen_app:news' %}">
                        <img src="{% static 'images/citizen-logo.png' %}">
                    </a>
                    <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar4">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar4">
                        <ul class="navbar-nav mr-auto pl-lg-4">
                            <li class="nav-item px-lg-2 dropdown d-menu">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="d-inline-block d-lg-none icon-width"><i class="far fa-caret-square-down"></i></span>Category
                                    <svg  id="arrow" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <polyline points="6 9 12 15 18 9"></polyline>
                                    </svg>
                                </a>
                                <div class="dropdown-menu shadow-sm sm-menu" aria-labelledby="dropdown01">
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=health">Health</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=sports">Sports</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=business">Business</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=technology">Technology</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=entertainment">Entertainment</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=science">Science</a>
                                </div>
                            </li>

                            <!--search starts here-->
                            <li class="nav-item px-lg-2">
                                <form action="" method="POST">
                                {% csrf_token %}
                                <input class="form-control-sm" type="text" placeholder="search.." name="search">
                                <button class="btn btn-outline-warning" type="submit" value="search">search</button>
                                </form>
                            </li>
                            <!--search ends here-->

                            <!--sort component-->
                            <li class="nav-item px-lg-2 dropdown d-menu">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="d-inline-block d-lg-none icon-width"><i class="far fa-caret-square-down"></i></span>Sort by
                                    <svg  id="arrow" xmlns="https://www.w3.org/TR/2018/CR-SVG2-20181004/" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <polyline points="6 9 12 15 18 9"></polyline>
                                    </svg>
                                </a>
                                <div class="dropdown-menu shadow-sm sm-menu" aria-labelledby="dropdown01">
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?">oldest</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=sports">popularity</a>
                                    <a class="dropdown-item" href="{% url 'citizen_app:news' %}?category=business">relevancy</a>
                                </div>
                            </li>
                            <!--end of sort-->

                            <!--report-->
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link px-lg-2" target="_blank" href="/payment">report
                                    <i style="font-size:30px, "class="fa">&#xf019;</i>
                                </a>
                            </li>
                            {% endif %}
                            <!--end of report-->


                            <!--user login sign-->
                            {% if user.is_authenticated %}

                            <li class="nav-item px-lg-2">
                                <span class="nav-link">Welcome, {{user.username}}</span>
                            </li>
                            <!--end of user login-->

                            <!--logout feature-->
                            <li class="nav-item px-lg-2">
                                <a class="nav-link" href="/logout">Logout</a>
                            </li>

                            {% else %}

                            <li class="nav-item px-lg-2">
                            <a class="nav-link" href="/login">Login</a>
                            </li>

                            {% endif %}
                            <!--end of logout-->

                        </ul>
                        <ul class="navbar-nav ml-auto mt-3 mt-lg-0">
                            <li class="nav-item"> 
                                <a class="nav-link" href="https://twitter.com/citizentvkenya?s=20">
                                    <i class="fa fa-twitter"></i>
                                    <span class="d-lg-none ml-3">Twitter</spa>
                                </a>
                            </li>
                            <li class="nav-item"> 
                                <a class="nav-link" href="https://www.facebook.com/CitizenTVKe/">
                                    <i class="fa fa-facebook"></i>
                                    <span class="d-lg-none ml-3">Facebook</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </a>
            </div>
        </nav>


        {% block content %}
    
        {% endblock %}
                        
        <!--footer starts here-->
        <footer data-v="">
            <div class="footer" data-v="">
                <div class="row" data-v="" style="height: 200px; background: black;">
                    <div class="container" data-v="">
                        <div class="container">
                            <div class="col-md-12 nopadding" data-v="">
                                <div class="col-md-4" data-v="">
                                    <h3 data-v="">About US</h3>
                                    <ul data-v="">
                                        <li data-v="">
                                        <i class="fa fa-chevron-right" data-v=""></i>
                                        <a target="_blank" href="" data-v="">Advertise with Us</a>
                                        </li>
                                        <li data-v="">
                                        <i class="fa fa-chevron-right" data-v=""></i>
                                        <a target="_blank" href="" data-v="">Privacy Policy</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-md-4" style="margin-top: 150px;" data-v="">
                                    <span class="down"> ©2021 Citizen Digital. All rights reserved </span>

                                </div>

                                <div class="col-md-4" data-v="">
                                    <h3 data-v="">contact info</h3>
                                    <ul data-v="">
                                        <li data-v="">
                                            <i class="fa fa-envelope" style="color: orange;" data-v=""></i>
                                            <a target="_blank" href="mailto:digitalsales@royalmedia.co.ke" data-v="">digitalsales@royalmedia.co.ke</a>
                                        </li>
                                        <li data-v="">
                                            <i class="fa fa-map-marker" style="color: orange;" data-v=""></i>
                                            <a target="_blank" href="" data-v="">Maalim Juma Road Off Dennis Pritt Road</a>
                                        </li>
                                    </ul>
                                </div>

                            
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>     
        </footer>
        <!--footer ends here-->
        <script src="{% static 'js/signup.js' %}"></script>
        <script src="{% static 'js/home.js' %}"></script>
        <script src="{% static 'nav.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    </body>

citizen_app/templates/payment.html
{% extends "nav.html" %}

{% block content %}
<div class="container" style="margin-top: 200px; align-items: center; margin-left: 450px; margin-bottom: 150px">
    <h1 Id="heading" style="margin-left: 100px; color: rgb(0, 195, 255);">subscription</h1>
    <hr style="margin-right: 700px; border: 1px solid orange;">
    <p style="font-size: 24px; color: grey; text-align: auto; margin-left: 130px;"><small style="font-size: 12px">USD</small> 5.00 / month</p>

    <div id="smart-button-container" style="margin-top: 20px; width: 300px; margin-left: 48px;">
      <div style="text-align: center;">
        <div id="paypal-button-container"></div>
      </div>
    </div>
    <div id="report" style="display: none">
      <a class="readmore" target="_blank" style="margin-bottom: 100px; margin-left: 160px; font-size: 20px;" href={% url 'citizen_app:report' %} rel="noopener">view report</a>
    </div>
  <script src="https://www.paypal.com/sdk/js?client-id=AX3NQAYH08vH1JrWCW2K3m08piFXO0PmmW6QmNvIV7h_8Yg75mJXg-IHM51li8A6ZL4X3RVk11WG-vHD&enable-funding=venmo&currency=USD" data-sdk-integration-source="button-factory"></script>
  <script>
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'pill',
          color: 'gold',
          layout: 'horizontal',
          label: 'paypal',
          
        },

        createOrder: function(data, actions) {
            
          return actions.order.create({
            purchase_units: [{"amount":{"currency_code":"USD","value":5}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
            
            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>';

            const report = document.getElementById('report').style.display = 'block';

            // Or go to another URL:  actions.redirect('thank_you.html');
            
          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>
  <p class="text-muted" style="margin-right: 650px; margin-top: 10px;">Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your report. </p>
</div>

  {% endblock %}

citizen_app/templates/readmore.html
{% extends 'nav.html' %}
{% load static %}
{% block content %}
<div class="container">
    <section class="" style="margin-top: 100px;">
        <div class="col mb-4">
            <div class="card h-100">
              <img src="{{data.urlToImage}}" alt="..." >
              <div class="card-body">
                <p><h5>{{data.title}}</h5></p>
                <!--paypal-->
                <p>{{ data.content }}</p>
                <p>{{data.url}}</p>
                <hr>
                <br>
                <small>date: {{data.publishedAt}}</small>
              </div>
            </div>
          </div>
    </section>
</div>

{% endblock %}